import type { Metadata } from 'next'
import { Epilogue } from 'next/font/google'
import './globals.css'
import { Root } from '../components/root'

const epilogue = Epilogue({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Storacha Network',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <Root>{children}</Root>
      </body>
    </html>
  )
}
