ALTER TABLE jobs 
DROP COLUMN IF EXISTS "points", 
DROP COLUMN IF EXISTS "size";

ALTER TABLE jobs 
ADD COLUMN "size" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN "points" DOUBLE PRECISION DEFAULT 0 NOT NULL;