name: PR triage labels

on:
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_target: # Enables labeling on PRs from forks by running with write permissions. Safe here because we only checkout the trusted base branch, not PR code.
    types: [synchronize, reopened, ready_for_review, converted_to_draft, review_requested]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label-awaiting-author:
    name: Manage awaiting-author/awaiting-review labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trusted base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }} # Always checkout the base branch (not PR code) for security when using pull_request_target

      - name: Apply/remove labels based on review state or new commits
        uses: actions/github-script@v7
        with:
          script: |
            const triage = require('./.github/scripts/pr-triage.js')
            await triage({ github, context, core })