name: PR triage labels

on:
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request:
    types: [synchronize, reopened, ready_for_review, converted_to_draft, review_requested]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label-awaiting-author:
    name: Manage awaiting-author/awaiting-review labels
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Apply/remove labels based on review state or new commits
        uses: actions/github-script@v7
        with:
          script: |
            const triage = require('./.github/scripts/pr-triage.js')
            await triage({ github, context, core })