name: Auto-mark and close stale PRs awaiting author

on:
  schedule:
    - cron: "0 3 * * *" # daily at 03:00 UTC
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Only act on PRs that are awaiting author updates
          only-pr-labels: awaiting-author

          # Exempt draft PRs entirely
          exempt-draft-pr: true

          # Timeline: mark stale after 10 days of inactivity, close 4 days later
          days-before-stale: 10
          days-before-close: 4

          # Labels and messages
          stale-pr-label: stale
          exempt-pr-labels: blocked,security,maintainer-will-finish
          remove-stale-when-updated: true

          stale-pr-message: |
            This pull request has been marked as stale because changes were requested and there has been no activity for 10 days.
            If you plan to continue, please push commits or leave a comment. Otherwise, this PR will be closed in 4 days.
            Maintainers can add an exemption label if needed.

          close-pr-message: |
            Closing this pull request due to inactivity after requested changes.
            If you’d like to continue, please push updates and ask a maintainer to reopen, or open a new PR referencing this one. Thanks!